<?php

/**
 * @file
 * ES Userforms module file with basic examples.
 */

/**
 * @defgroup es_userform Example: AJAX
 * @ingroup ici
 * @{
 * These examples show basic AJAX concepts.
 *
 * General documentation is available at
 * @link ajax AJAX Framework documentation @endlink and at the
 * @link http://drupal.org/node/752056 AJAX Forms handbook page @endlink.
 *
 * The several examples here demonstrate basic AJAX usage.
 */

/**
 * @} End of "defgroup es_userform".
 */
